### ISSUE TITLE
Corrupted code

### ISSUE THREAD

**Issue by tk2themax** [analogdevicesinc/EVAL-ADICUP3029#17]
ADuCM3029_demo_cn0428_cn0429.hex is corrupted.  Verified against a fresh version from issuer.

**Comment by scotthuntanalog** [comment]
Hello,

I have verified that the ADuCM3029_demo_cn0428_cn0429.hex runs correctly when I download the zip archive, unzip the files, and load it onto my ADICUP3029 with mbed. How did you download the file from GitHub? Did you unzip the archive before dragging the file to the daplink drive? Otherwise the compression from the zip could look like corruption.

Please try downloading the zip archive from https://github.com/analogdevicesinc/EVAL-ADICUP3029/archive/master.zip , then extract/unzip the archive, and try loading the hex file onto the EVAL-ADICUP3029. Let me know if this solves your issue.

Thanks,
Scott

**Comment by scotthuntanalog** [comment]
Hello,

I have been told there is also a way to do this without downloading the whole archive. 

1. Go into the .hex file: https://github.com/analogdevicesinc/EVAL-ADICUP3029/blob/master/projects/ADuCM3029_demo_cn0428_cn0429/Release/ADuCM3029_demo_cn0428_cn0429.hex 

2. Right click the "Raw" button

3. Click "Save Link As..." (or similar, actual text varies depending on the browser)

4. Just to double-check, make sure the size of the file you downloaded matches the file size at the top left of the page (currently 311 kB).

I have just verified that this method works on my end as well by downloading the file this way and programming it onto my ADICUP3029 and testing it.

If the first time, you had tried to right click the link in the /Releases/ folder and used the Save As from there, it would not have worked (from inspecting the text, it seems to save an html document).

I'm marking this issue closed for now, but let me know if you still have any issue.

Thanks,
Scott
